#include "../includes/erros.hpp"

ServerErrorHandler::ServerErrorHandler() {
	initializeErrorMessages();
}

// Inicializa o mapa de mensagens de erro
void ServerErrorHandler::initializeErrorMessages() {
	errorMessages[400] = "Bad Request";
	errorMessages[401] = "Unauthorized";
	errorMessages[403] = "Forbidden";
	errorMessages[404] = "Not Found";
	errorMessages[405] = "Method Not Allowed";
	errorMessages[406] = "Not Acceptable";
	errorMessages[407] = "Proxy Authentication Required";
	errorMessages[408] = "Request Timeout";
	errorMessages[409] = "Conflict";
	errorMessages[410] = "Gone";
	errorMessages[411] = "Length Required";
	errorMessages[412] = "Precondition Failed";
	errorMessages[413] = "Payload Too Large";
	errorMessages[414] = "URI Too Long";
	errorMessages[415] = "Unsupported Media Type";
	errorMessages[416] = "Range Not Satisfiable";
	errorMessages[417] = "Expectation Failed";
	errorMessages[418] = "I'm a teapot";
	errorMessages[421] = "Misdirected Request";
	errorMessages[422] = "Unprocessable Entity";
	errorMessages[423] = "Locked";
	errorMessages[424] = "Failed Dependency";
	errorMessages[426] = "Upgrade Required";
	errorMessages[428] = "Precondition Required";
	errorMessages[429] = "Too Many Requests";
	errorMessages[431] = "Request Header Fields Too Large";
	errorMessages[451] = "Unavailable For Legal Reasons";
	errorMessages[500] = "Internal Server Error";
	errorMessages[501] = "Not Implemented";
	errorMessages[502] = "Bad Gateway";
	errorMessages[503] = "Service Unavailable";
	errorMessages[504] = "Gateway Timeout";
	errorMessages[505] = "HTTP Version Not Supported";
	errorMessages[506] = "Variant Also Negotiates";
	errorMessages[507] = "Insufficient Storage";
	errorMessages[508] = "Loop Detected";
	errorMessages[510] = "Not Extended";
	errorMessages[511] = "Network Authentication Required";
	// Adicionar mais erros conforme vamos vendo que aparecem
}

std::string ServerErrorHandler::generateErrorPage(int errorCode, const std::string& errorMessage)
{
	std::ostringstream html;
	html << "<!DOCTYPE html>"
		 << "<html lang=\"en\">"
		 << "<head>"
		 << "<meta charset=\"UTF-8\">"
		 << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		 << "<style>"
		 << "body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #ADD8E6; }"
		 << "h1 { font-size: 50px; }"
		 << ".errorCode { color: red; }"
		 << "p { font-size: 20px; color: #333; }"
		 << ".error-container { max-width: 600px; margin: auto; }"
		 << "</style>"
		 << "<title>Error " << errorCode << "</title>"
		 << "</head>"
		 << "<body>"
		 << "<div class=\"error-container\">"
		 << "<h1 class=\"errorCode\">Error " << errorCode << "</h1>"
		 << "<p>" << errorMessage << "</p>"
		 << "<br>"
		 << "<button onclick=\"location.href='/'\">Home</button>"
		 << "</div>"
		 << "</body>"
		 << "</html>";
	return html.str();
}




// Gera uma página de erro HTML baseada no código de erro
std::string ServerErrorHandler::generateErrorPage(int errorCode) {
	std::map<int, std::string>::iterator it = errorMessages.find(errorCode);
	if (it != errorMessages.end()) {
		return generateErrorPage(errorCode, it->second);
	} else {
		return generateErrorPage(500, "Internal Server Error"); // Erro padrão
	}
}

std::string ServerErrorHandler::getErrorMessage(int errorCode)
{
	std::map<int, std::string>::iterator it = errorMessages.find(errorCode);
	if (it != errorMessages.end())
	{
		return it->second;
	}
	else
	{
		return "Unknown Error"; // Default error message
	}
}

std::string ServerErrorHandler::generateIndex(const std::string& name)
{
	std::ostringstream html;
	html << "<!DOCTYPE html>"
		 << "<html lang=\"en\">"
		 << "<head>"
		 << "<meta charset=\"UTF-8\">"
		 << "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
		 << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		 << "<title>Webserver Home</title>"
		 << "<style>"
		 << "body {"
		 << "font-family: Arial, sans-serif;"
		 << "display: flex;"
		 << "justify-content: center;"
		 << "align-items: center;"
		 << "height: 70vh;"
		 << "margin: 0;"
		 << "background-color: #01012b;"
		 << "}"
		 << "@keyframes pulse {"
		 << "0% { transform: scale(1); }"
		 << "50% { transform: scale(1.1); }"
		 << "100% { transform: scale(1); }"
		 << "}"
		 << "h1 {"
		 << "font-family: \"Arial\", monospace;"
		 << "font-size: 4.5em;"
		 << "font-weight: 900;"
		 << "animation: pulse 3s infinite;"
		 << "}"
		 << ".container {"
		 << "text-align: center;"
		 << "max-width: 850px;"
		 << "width: 100%;"
		 << "background-color: #94bbd0;"
		 << "padding: 20px;"
		 << "border-radius: 10px;"
		 << "box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);"
		 << "}"
		 << ".buttons {"
		 << "font-size: 20px;"
		 << "padding: 10px 20px;"
		 << "border: none;"
		 << "border-radius: 8px;"
		 << "cursor: pointer;"
		 << "margin-bottom: 20px;"
		 << "margin-left: 10px;"
		 << "margin-top: 5px;"
		 << "}"
		 << ".credits_1 {"
		 << "text-align: center;"
		 << "padding: 15px;"
		 << "background-color: #5f94c9;"
		 << "margin-top: 20px;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".credits_2 {"
		 << "max-width: 850px;"
		 << "margin: auto;"
		 << "}"
		 << "a[href*=\"https://profile.intra.42.fr\"] {"
		 << "color: rgb(7, 7, 114);"
		 << "}"
		 << "a[href*=\"https://profile.intra.42.fr\"]:hover {"
		 << "color: rgb(255, 255, 255);"
		 << "}"
		 << "a[href*=\"https://github.com\"] {"
		 << "color: rgb(7, 7, 114);"
		 << "}"
		 << "a[href*=\"https://github.com\"]:hover {"
		 << "color: rgb(255, 255, 255);"
		 << "}"
		 << ".glow-on-hover {"
		 << "border: none;"
		 << "outline: none;"
		 << "color: #fff;"
		 << "cursor: pointer;"
		 << "position: relative;"
		 << "z-index: 0;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".glow-on-hover:before {"
		 << "content: '';"
		 << "background: linear-gradient(45deg, #ff0000, #ff0000);"
		 << "position: absolute;"
		 << "top: -2px;"
		 << "left:-2px;"
		 << "background-size: 400%;"
		 << "z-index: -1;"
		 << "filter: blur(5px);"
		 << "width: calc(100% + 5px);"
		 << "height: calc(100% + 5px);"
		 << "animation: glowing 20s linear infinite;"
		 << "opacity: 0;"
		 << "transition: opacity .3s ease-in-out;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".glow-on-hover:active {"
		 << "color: #000000;"
		 << "}"
		 << ".glow-on-hover:active:after {"
		 << "background: #72bae0;"
		 << "}"
		 << ".glow-on-hover:hover:before {"
		 << "opacity: 1;"
		 << "}"
		 << ".glow-on-hover:after {"
		 << "z-index: -1;"
		 << "content: '';"
		 << "position: absolute;"
		 << "width: 100%;"
		 << "height: 100%;"
		 << "background: #090345;"
		 << "left: 0;"
		 << "top: 0;"
		 << "border-radius: 10px;"
		 << "}"
		 << "</style>"
		 << "<link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"favicon.ico\" >"
		 << "</head>"
		 << "<body>"
		 << "<div class=\"container\">"
		 << "<h1>WebServer</h1>"
		 << "<a href=\"/" << name << " \"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>"
		 << "<a href=\"/get.html\"><button class=\"buttons glow-on-hover\"><b>Get Page</b></button></a>"
		 << "<a href=\"/post.html\"><button class=\"buttons glow-on-hover\"><b>Post Page</b></button></a>"
		 << "<a href=\"/upload.html\"><button class=\"buttons glow-on-hover\"><b>Upload Page</b></button></a>"
		 << "<a href=\"/delete.html\"><button class=\"buttons glow-on-hover\"><b>Delete Page</b></button></a>"
		 << "<div class=\"credits_1\">"
		 << "<h3>CREDITS</h3>"
		 << "<table class=\"credits_2\">"
		 << "<tr>"
		 << "<td style=\"text-align: center;\"><b>Frederico Bajouco</b> </b> [ </b></td>"
		 << "<td style=\"text-align: center;\"><a href=\"https://profile.intra.42.fr/users/fde-carv\">Intra 42</a> </b> | </b> </td>"
		 << "<td style=\"text-align: center;\"><a href=\"https://github.com/krammersf\">Github</a> </b> ] </b> </td>"
		 << "<td style=\"text-align: center;\"></td>"
		 << "<td style=\"text-align: center;\"></td>"
		 << "<td style=\"text-align: center;\"></td>"
		 << "<td style=\"text-align: center;\"><b>Filipa Borges</b></b> [ </b></td>"
		 << "<td style=\"text-align: center;\"><a href=\"https://profile.intra.42.fr/users/firibeir\">Intra 42</a> </b> | </b> </td>"
		 << "<td style=\"text-align: center;\"><a href=\"https://github.com/fiborges\">Github</a> </b> ] </b> </td>"
		 << "<td style=\"text-align: center;\"></td>"
		 << "<td style=\"text-align: center;\"></td>"
		 << "<td style=\"text-align: center;\"></td>"
		 << "<td style=\"text-align: center;\"><b>Bruno Soares</b></b> [ </b></td>"
		 << "<td style=\"text-align: center;\"><a href=\"https://profile.intra.42.fr/users/brolivei\">Intra 42</a> </b> | </b> </td>"
		 << "<td style=\"text-align: center;\"><a href=\"https://github.com/BrunoAlone\">Github</a> </b> ] </b> </td>"
		 << "</tr>"
		 << "</table>"
		 << "</div>"
		 << "</div>"
		 << "</body>"
		 << "</html>";
	return html.str();
}

std::string ServerErrorHandler::generateDelete()
{
	std::ostringstream html;
	html << "<!DOCTYPE html>"
		 << "<html lang=\"en\">"
		 << "<head>"
		 << "<meta charset=\"UTF-8\">"
		 << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		 << "<title>Delete a file from the upload directory</title>"
		 << "<style>"
		 << "body {"
		 << "font-family: Arial, sans-serif;"
		 << "display: flex;"
		 << "justify-content: center;"
		 << "align-items: center;"
		 << "height: 70vh;"
		 << "margin: 0;"
		 << "background-color: #01012b;"
		 << "}"
		 << "h1 {"
		 << "font-family: \"Arial\", monospace;"
		 << "font-size: 2.5em;"
		 << "font-weight: 900;"
		 << "}"
		 << ".container {"
		 << "text-align: center;"
		 << "max-width: 850px;"
		 << "width: 100%;"
		 << "background-color: #94bbd0;"
		 << "padding: 20px;"
		 << "border-radius: 10px;"
		 << "box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);"
		 << "}"
		 << ".buttons {"
		 << "font-size: 20px;"
		 << "padding: 10px 20px;"
		 << "border: none;"
		 << "border-radius: 8px;"
		 << "cursor: pointer;"
		 << "margin-bottom: 20px;"
		 << "margin-left: 10px;"
		 << "margin-top: 5px;"
		 << "}"
		 << ".home-button {"
		 << "display: flex;"
		 << "justify-content: center;"
		 << "margin-bottom: 20px;"
		 << "}"
		 << ".file-message {"
		 << "margin-top: 10px;"
		 << "margin-bottom: 10px;"
		 << "padding-left: 4em;"
		 << "text-align: left;"
		 << "}"
		 << ".file-message strong {"
		 << "font-weight: bold;"
		 << "color: rgb(255, 255, 255);"
		 << "font-size: 20px;"
		 << "}"
		 << ".file-name {"
		 << "color: red;"
		 << "}"
		 << ".glow-on-hover {"
		 << "border: none;"
		 << "outline: none;"
		 << "color: #fff;"
		 << "cursor: pointer;"
		 << "position: relative;"
		 << "z-index: 0;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".glow-on-hover:before {"
		 << "content: '';"
		 << "background: linear-gradient(45deg, #ff0000, #ff0000);"
		 << "position: absolute;"
		 << "top: -2px;"
		 << "left: -2px;"
		 << "background-size: 400%;"
		 << "z-index: -1;"
		 << "filter: blur(5px);"
		 << "width: calc(100% + 5px);"
		 << "height: calc(100% + 5px);"
		 << "animation: glowing 20s linear infinite;"
		 << "opacity: 0;"
		 << "transition: opacity .3s ease-in-out;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".glow-on-hover:active {"
		 << "color: #000000;"
		 << "}"
		 << ".glow-on-hover:active:after {"
		 << "background: #72bae0;"
		 << "}"
		 << ".glow-on-hover:hover:before {"
		 << "opacity: 1;"
		 << "}"
		 << ".glow-on-hover:after {"
		 << "z-index: -1;"
		 << "content: '';"
		 << "position: absolute;"
		 << "width: 100%;"
		 << "height: 100%;"
		 << "background: #090345;"
		 << "left: 0;"
		 << "top: 0;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".delete-button {"
		 << "background-color: #8d0000 !important;"
		 << "color: #ffffff !important;"
		 << "font-weight: bold;"
		 << "}"
		 << "</style>"
		 << "</head>"
		 << "<body>"
		 << "<div class=\"container\">"
		 << "<h1>Delete a file from the upload directory</h1>"
		 << "<div class=\"home-button\">"
		 << "<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>"
		 << "</div>"
		 << "<div class=\"button-group\">"
		 << "<input type=\"file\" name=\"file\" id=\"file\" class=\"buttons glow-on-hover\">"
		 << "<button onclick=\"deleteFile()\" class=\"buttons glow-on-hover delete-button\">Delete</button>"
		 << "</div>"
		 << "<div class=\"file-message glow-on-hover\" id=\"file-message\"><strong>Selected file:</strong></div>"
		 << "</div>"
		 << "<script>"
		 << "function deleteFile() {"
		 << "var input = document.getElementById('file');"
		 << "var file = input.files[0];"
		 << "if (!file) {"
		 << "document.getElementById('file-message').innerHTML = '<strong>Selected file:</strong>';"
		 << "alert('Please select a file to delete.');"
		 << "return;"
		 << "}"
		 << "var xhr = new XMLHttpRequest();"
		 << "xhr.open('DELETE', '/delete.html?file=' + encodeURIComponent(file.name), true);"
		 << "xhr.onreadystatechange = function () {"
		 << "if (xhr.readyState == 4 && xhr.status == 200) {"
		 << "alert('File deleted successfully');"
		 << "} else if (xhr.readyState == 4) {"
		 << "alert('Error deleting file: ' + xhr.responseText);"
		 << "}"
		 << "};"
		 << "xhr.send();"
		 << "document.getElementById('file-message').innerHTML = '<strong>Selected file: </strong> <span class=\"file-name\">' + file.name + '</span>';"
		 << "input.value = '';"
		 << "}"
		 << "</script>"
		 << "</body>"
		 << "</html>";
	return html.str();
}

std::string ServerErrorHandler::generateGet()
{
	std::ostringstream html;
	html << "<!DOCTYPE html>"
		 << "<html lang=\"en\">"
		 << "<head>"
		 << "<meta charset=\"UTF-8\">"
		 << "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
		 << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		 << "<title>Formulário POST</title>"
		 << "<style>"
		 << "body {"
		 << "font-family: Arial, sans-serif;"
		 << "display: flex;"
		 << "justify-content: center;"
		 << "align-items: center;"
		 << "height: 70vh;"
		 << "margin: 0;"
		 << "background-color: #01012b;"
		 << "}"
		 << "@keyframes pulse {"
		 << "0% {"
		 << "transform: scale(1);"
		 << "}"
		 << "50% {"
		 << "transform: scale(1.1);"
		 << "}"
		 << "100% {"
		 << "transform: scale(1);"
		 << "}"
		 << "}"
		 << "h1 {"
		 << "font-family: \"Arial\", monospace;"
		 << "font-size: 2.5em;"
		 << "font-weight: 900;"
		 << "}"
		 << ".container {"
		 << "text-align: center;"
		 << "max-width: 850px;"
		 << "width: 100%;"
		 << "background-color: #94bbd0;"
		 << "padding: 20px;"
		 << "border-radius: 10px;"
		 << "box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);"
		 << "}"
		 << ".buttons {"
		 << "font-size: 20px;"
		 << "padding: 10px 20px;"
		 << "border: none;"
		 << "border-radius: 8px;"
		 << "cursor: pointer;"
		 << "margin-bottom: 20px;"
		 << "margin-left: 10px;"
		 << "margin-top: 5px;"
		 << "}"
		 << ".credits_1 {"
		 << "text-align: center;"
		 << "padding: 15px;"
		 << "background-color: #5f94c9;"
		 << "margin-top: 20px;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".credits_2 {"
		 << "max-width: 850px;"
		 << "margin: auto;"
		 << "}"
		 << "a[href*=\"https://profile.intra.42.fr\"] {"
		 << "color: rgb(7, 7, 114);"
		 << "}"
		 << "a[href*=\"https://profile.intra.42.fr\"]:hover {"
		 << "color: rgb(255, 255, 255);"
		 << "}"
		 << "a[href*=\"https://github.com\"] {"
		 << "color: rgb(7, 7, 114);"
		 << "}"
		 << "a[href*=\"https://github.com\"]:hover {"
		 << "color: rgb(255, 255, 255);"
		 << "}"
		 << ".glow-on-hover {"
		 << "border: none;"
		 << "outline: none;"
		 << "color: #fff;"
		 << "cursor: pointer;"
		 << "position: relative;"
		 << "z-index: 0;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".glow-on-hover:before {"
		 << "content: '';"
		 << "background: linear-gradient(45deg, #ff0000, #ff0000);"
		 << "position: absolute;"
		 << "top: -2px;"
		 << "left:-2px;"
		 << "background-size: 400%;"
		 << "z-index: -1;"
		 << "filter: blur(5px);"
		 << "width: calc(100% + 5px);"
		 << "height: calc(100% + 5px);"
		 << "animation: glowing 20s linear infinite;"
		 << "opacity: 0;"
		 << "transition: opacity .3s ease-in-out;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".glow-on-hover:active {"
		 << "color: #000000"
		 << "}"
		 << ".glow-on-hover:active:after {"
		 << "background: #72bae0;"
		 << "}"
		 << ".glow-on-hover:hover:before {"
		 << "opacity: 1;"
		 << "}"
		 << ".glow-on-hover:after {"
		 << "z-index: -1;"
		 << "content: '';"
		 << "position: absolute;"
		 << "width: 100%;"
		 << "height: 100%;"
		 << "background: #090345;"
		 << "left: 0;"
		 << "top: 0;"
		 << "border-radius: 10px;"
		 << "}"
		 << ".upload-button {"
		 << "background-color: #8d0000;"
		 << "color: #ffffff;"
		 << "font-weight: bold"
		 << "}"
		 << ".large-bold {"
		 << "font-size: 2em;"
		 << "font-weight: bold;"
		 << "}"
		 << ".large-bold2 {"
		 << "font-size: 1.2em;"
		 << "font-weight: bold;"
		 << "}"
		 << ".large-bold3 {"
		 << "font-weight: bold;"
		 << "display: inline;"
		 << "}"
		 << "</style>"
		 << "</head>"
		 << "<body>"
		 << "<div class=\"container\">"
		 << "<h1>Get Page</h1>"
		 << "<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>"
		 << "<form action=\"http://localhost:8080\" method=\"post\"><br>"
		 << "<div class=\"large-bold\">Webserv<br></div><br>"
		 << "<div class=\"large-bold2\">This is when you finally understand why a URL startswith HTTP<br></div><br>"
		 << "<div class=\"large-bold3\">Summary:</div>"
		 << "This project is about writing your own HTTP server."
		 << "You will be able to test it with an actual browser."
		 << "HTTP is one of the most used protocols on the internet."
		 << "Knowing its arcane will be useful, even if you won’t be working on a website."
		 << "Version: 21.2"
		 << "</form>"
		 << "</div>"
		 << "</body>"
		 << "</html>";
	return html.str();
}

std::string ServerErrorHandler::generatePost()
{
	std::ostringstream html;
	html << "<!DOCTYPE html>"
		<< "<html lang=\"en\">"
		<< "<head>"
		<< "<meta charset=\"UTF-8\">"
		<< "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
		<< "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		<< "<title>Formulário POST</title>"
		<< "<style>"
		<< "body {"
		<< "font-family: Arial, sans-serif;"
		<< "display: flex;"
		<< "justify-content: center;"
		<< "align-items: center;"
		<< "height: 70vh;"
		<< "margin: 0;"
		<< "background-color: #01012b;"
		<< "}"
		<< "@keyframes pulse {"
		<< "0% {"
		<< "transform: scale(1);"
		<< "}"
		<< "50% {"
		<< "transform: scale(1.1);"
		<< "}"
		<< "100% {"
		<< "transform: scale(1);"
		<< "}"
		<< "}"
		<< "h1 {"
		<< "font-family: \"Arial\", monospace;"
		<< "font-size: 2.5em;"
		<< "font-weight: 900;"
		<< "}"
		<< ".container {"
		<< "text-align: center;"
		<< "max-width: 850px;"
		<< "width: 100%;"
		<< "background-color: #94bbd0;"
		<< "padding: 20px;"
		<< "border-radius: 10px;"
		<< "box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);"
		<< "}"
		<< ".buttons {"
		<< "font-size: 20px;"
		<< "padding: 10px 20px;"
		<< "border: none;"
		<< "border-radius: 8px;"
		<< "cursor: pointer;"
		<< "margin-bottom: 20px;"
		<< "margin-left: 10px;"
		<< "margin-top: 5px;"
		<< "}"
		<< ".credits_1 {"
		<< "text-align: center;"
		<< "padding: 15px;"
		<< "background-color: #5f94c9;"
		<< "margin-top: 20px;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".credits_2 {"
		<< "max-width: 850px;"
		<< "margin: auto;"
		<< "}"
		<< "a[href*=\"https://profile.intra.42.fr\"] {"
		<< "color: rgb(7, 7, 114);"
		<< "}"
		<< "a[href*=\"https://profile.intra.42.fr\"]:hover {"
		<< "color: rgb(255, 255, 255);"
		<< "}"
		<< "a[href*=\"https://github.com\"] {"
		<< "color: rgb(7, 7, 114);"
		<< "}"
		<< "a[href*=\"https://github.com\"]:hover {"
		<< "color: rgb(255, 255, 255);"
		<< "}"
		<< ".glow-on-hover {"
		<< "border: none;"
		<< "outline: none;"
		<< "color: #fff;"
		<< "position: relative;"
		<< "z-index: 0;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".glow-on-hover:before {"
		<< "content: '';"
		<< "background: linear-gradient(45deg, #ff0000, #ff0000);"
		<< "position: absolute;"
		<< "top: -2px;"
		<< "left:-2px;"
		<< "background-size: 400%;"
		<< "z-index: -1;"
		<< "filter: blur(5px);"
		<< "width: calc(100% + 5px);"
		<< "height: calc(100% + 5px);"
		<< "animation: glowing 20s linear infinite;"
		<< "opacity: 0;"
		<< "transition: opacity .3s ease-in-out;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".glow-on-hover:active {"
		<< "color: #000000"
		<< "}"
		<< ".glow-on-hover:active:after {"
		<< "background: #72bae0;"
		<< "}"
		<< ".glow-on-hover:hover:before {"
		<< "opacity: 1;"
		<< "}"
		<< ".glow-on-hover:after {"
		<< "z-index: -1;"
		<< "content: '';"
		<< "position: absolute;"
		<< "width: 100%;"
		<< "height: 100%;"
		<< "background: #090345;"
		<< "left: 0;"
		<< "top: 0;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".upload-button {"
		<< "background-color: #8d0000;"
		<< "color: #ffffff;"
		<< "font-weight: bold"
		<< "}"
		<< ".submit-button {"
		<< "background-color: #8d0000;"
		<< "color: #ffffff;"
		<< "font-weight: bold"
		<< "}"
		<< "</style>"
		<< "</head>"
		<< "<body>"
		<< "<div class=\"container\">"
		<< "<h1>Formulário POST</h1>"
		<< "<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>"
		<< "<form action=\"/post\" method=\"post\"><br>"
		<< "<label for=\"key1\">Chave 1:</label>"
		<< "<input type=\"text\" id=\"key1\" name=\"key1\"><br><br><br>"
		<< "<label for=\"key2\">Chave 2:</label>"
		<< "<input type=\"text\" id=\"key2\" name=\"key2\"><br><br><br>"
		<< "<input type=\"submit\" value=\"Enviar\" class=\"buttons glow-on-hover submit-button\">"
		<< "</form>"
		<< "</div>"
		<< "</body>"
		<< "</html>";
	return html.str();
}

std::string ServerErrorHandler::generateUpload()
{
	std::ostringstream html;
	html << "<!DOCTYPE html>"
		<< "<html lang=\"en\">"
		<< "<head>"
		<< "<meta charset=\"UTF-8\">"
		<< "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
		<< "<title>File Upload</title>"
		<< "<style>"
		<< "body {"
		<< "font-family: Arial, sans-serif;"
		<< "display: flex;"
		<< "justify-content: center;"
		<< "align-items: center;"
		<< "height: 70vh;"
		<< "margin: 0;"
		<< "background-color: #01012b;"
		<< "}"
		<< "@keyframes pulse {"
		<< "0% {"
		<< "transform: scale(1);"
		<< "}"
		<< "50% {"
		<< "transform: scale(1.1);"
		<< "}"
		<< "100% {"
		<< "transform: scale(1);"
		<< "}"
		<< "}"
		<< "h1 {"
		<< "font-family: \"Arial\", monospace;"
		<< "font-size: 2.5em;"
		<< "font-weight: 900;"
		// << "animation: pulse 3s infinite;" // This line is commented out in the original HTML
		<< "}"
		<< ".container {"
		<< "text-align: center;"
		<< "max-width: 850px;"
		<< "width: 100%;"
		<< "background-color: #94bbd0;"
		<< "padding: 20px;"
		<< "border-radius: 10px;"
		<< "box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);"
		<< "}"
		<< ".buttons {"
		<< "font-size: 20px;"
		// Background color and color are commented out in the original HTML
		<< "padding: 10px 20px;"
		<< "border: none;"
		<< "border-radius: 8px;"
		<< "cursor: pointer;"
		<< "margin-bottom: 20px;"
		<< "margin-left: 10px;"
		<< "margin-top: 5px;"
		<< "}"
		<< ".credits_1 {"
		<< "text-align: center;"
		<< "padding: 15px;"
		<< "background-color: #5f94c9;"
		<< "margin-top: 20px;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".credits_2 {"
		<< "max-width: 850px;"
		<< "margin: auto;"
		<< "}"
		<< "a[href*=\"https://profile.intra.42.fr\"] {"
		<< "color: rgb(7, 7, 114);"
		<< "}"
		<< "a[href*=\"https://profile.intra.42.fr\"]:hover {"
		<< "color: rgb(255, 255, 255);"
		<< "}"
		<< "a[href*=\"https://github.com\"] {"
		<< "color: rgb(7, 7, 114);"
		<< "}"
		<< "a[href*=\"https://github.com\"]:hover {"
		<< "color: rgb(255, 255, 255);"
		<< "}"
		<< ".glow-on-hover {"
		<< "border: none;"
		<< "outline: none;"
		<< "color: #fff;"
		<< "cursor: pointer;"
		<< "position: relative;"
		<< "z-index: 0;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".glow-on-hover:before {"
		<< "content: '';"
		<< "background: linear-gradient(45deg, #ff0000, #ff0000);"
		<< "position: absolute;"
		<< "top: -2px;"
		<< "left:-2px;"
		<< "background-size: 400%;"
		<< "z-index: -1;"
		<< "filter: blur(5px);"
		<< "width: calc(100% + 5px);"
		<< "height: calc(100% + 5px);"
		<< "animation: glowing 20s linear infinite;"
		<< "opacity: 0;"
		<< "transition: opacity .3s ease-in-out;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".glow-on-hover:active {"
		<< "color: #000000"
		<< "}"
		<< ".glow-on-hover:active:after {"
		<< "background: #72bae0;"
		<< "}"
		<< ".glow-on-hover:hover:before {"
		<< "opacity: 1;"
		<< "}"
		<< ".glow-on-hover:after {"
		<< "z-index: -1;"
		<< "content: '';"
		<< "position: absolute;"
		<< "width: 100%;"
		<< "height: 100%;"
		<< "background: #090345;"
		<< "left: 0;"
		<< "top: 0;"
		<< "border-radius: 10px;"
		<< "}"
		<< ".upload-button {"
		<< "background-color: #0f5905;"
		<< "color: #ffffff;"
		<< "font-weight: bold;"
		<< "}"
		<< "</style>"
		<< "<link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"favicon.ico\" >"
		<< "</head>"
		<< "<body>"
		<< "<div class=\"container\">"
		<< "<h1>Upload a File</h1>"
		<< "<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>"
		<< "<form action=\"/cgi-bin/UploadScript.py/uploads\" method=\"post\" enctype=\"multipart/form-data\">"
		<< "<input type=\"file\" name=\"file\" id=\"file\" class=\"buttons glow-on-hover\">"
		<< "<input type=\"submit\" value=\"Upload\" class=\"buttons glow-on-hover upload-button\">"
		<< "</form>"
		<< "</div>"
		<< "</body>"
		<< "</html>";
	return html.str();
}