server {
	listen 8080
	server_name SERVER_1
	root YoupiBanane
	#index index.html
	autoindex on
	client_body_size 100k
	#	Se quisermos dar GET dos ficheiros que foram dado upload, temos de colocar a pasta
	#fora de cgi-bin, com caminho relativo ou absoluto
	#upload_dir ./../uploads
	upload_dir /home/brolivei/Documents/WebServer_WorkingBranch/WebServer/TesteFolder/uploads
	error_page 405 /4xx.html
	error_page 500 502 503 504 /50x.html

	location / {
		root YoupiBanane
		limit_except GET
	}

	location /uploads/ {
		root YoupiBanane
		limit_except GET
	}

	location /TesteLocation/ {
		root YoupiBanane
		limit_except GET
	}

	# Tem que estar configurado se quisermos usar scripts
	location /cgi-bin/ {
		root YoupiBanane
		#From the place where the server is running
		cgi_pass /TesteFolder/cgi-bin
		limit_except POST GET
	}
}
