server {
	listen 8080
	server_name SERVER_1
	root TesteFolder
	index index.html
	autoindex on
	client_body_size 100k
	#	Se quisermos dar GET dos ficheiros que foram dado upload, temos de colocar a pasta
	#fora de cgi-bin, com caminho relativo ou absoluto
	#upload_dir ./../uploads
	upload_dir /home/firibeir/Desktop/WebServer/uploads
	error_page 405 /4xx.html
	error_page 500 502 503 504 /50x.html

	location / {
		root TesteFolder
		limit_except POST GET DELETE
	}

	location /uploads/ {
		root TesteFolder
		limit_except GET DELETE
	}

	location /TesteLocation/ {
		root TesteFolder
		limit_except GET
	}

	# Tem que estar configurado se quisermos usar scripts
	location /cgi-bin/ {
		root TesteFolder
		#From the place where the server is running
		cgi_pass /cgi-bin
		limit_except POST GET
	}
}
