server {
	listen 8080
	server_name SERVER_1
	root TesteFolder
	index index.html
	autoindex on
	client_body_size 100k
	upload_dir /uploads
	error_page 405 /4xx.html
	error_page 500 502 503 504 /50x.html

	location / {
		root TesteFolder
		limit_except POST GET DELETE
	}
	location /cgi-bin/uploads/ {
		root TesteFolder
		limit_except GET
	}
	location /cgi-bin/ {
		cgi_pass /TesteFolder/cgi-bin
		limit_except POST GET
	}
}
